# This is a sample build configuration for Ruby.
# Check our guides at https://confluence.atlassian.com/x/8r-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ruby:2.4.5

pipelines:
  default:
    - step:
        
        script:
        - bundle install
        - rspec
        - cucumber
        - git push https://heroku:bbe86632-4a76-4451-9393-9460c8db502d@git.heroku.com/dots-andboxes.git HEAD



definitions:
  caches:
    bundler: ./Gemfile
